A_POSITION = 1
AN_OWNER = 1
NOT_AN_OWNER = 2
A_SYMBOL = 3
EMPTY_SYMBOL = ' '
A_ROW_NUMBER = 1
A_COL_NUMBER = 2
A_POSITION_STRING = 'B,2'
POSITION_STRING_COL = 1
POSITION_STRING_ROW = 1
NOT_A_POSITION_STRING = 'Z,4'
A_PLAYER = 'PLAYER'
A_PLAYER_NAME = 'PLAYER'
A_COMPUTER_NAME = 'COMPUTER'
A_PLAYER_NUMBER = 1
AN_OUTPUT = 1
AN_INPUT = "INPUT"
CELL_CONTENT = 1
BOARD_MESSAGE = "\t1  #{CELL_CONTENT}  |  #{CELL_CONTENT}  \n" +
                "\t -----------------\n" +
                "\t2  #{CELL_CONTENT}  |  #{CELL_CONTENT}  \n" +
                "\t -----------------\n" +
                "\t3  #{CELL_CONTENT}  |  #{CELL_CONTENT}  \n"
ALL_POSITIONS = ['A,1', 'B,1', 'C,1', 'A,2', 'B,2', 'C,2', 'A,3', 'B,3', 'C,3']
SOME_POSITIONS = ['B,1', 'A,3', 'C,2']
ALL_EXCEPT_SOME_POSITIONS = ['A,1', 'C,1', 'A,2', 'B,2', 'B,3', 'C,3']
PLAYER_1 = '1'
PLAYER_1_SYMBOL = 'X'
PLAYER_2 = '2'
PLAYER_2_SYMBOL = 'O'
PLAYER_1_DRAW_POSITIONS = ['A,1', 'A,3', 'B,2', 'C,2']
PLAYER_2_DRAW_POSITIONS = ['A,2', 'B,1', 'B,3', 'C,1', 'C,3']
FIRST_ROW_WIN_POSITIONS = ['A,1', 'B,1', 'C,1']
SECOND_ROW_WIN_POSITIONS = ['A,2', 'B,2', 'C,2']
THIRD_ROW_WIN_POSITIONS = ['A,3', 'B,3', 'C,3']
FIRST_COL_WIN_POSITIONS = ['A,1', 'A,2', 'A,3']
SECOND_COL_WIN_POSITIONS = ['B,1', 'B,2', 'B,3']
THIRD_COL_WIN_POSITIONS = ['C,1', 'C,2', 'C,3']
DIAGONAL_UP_WIN_POSITIONS = ['A,1', 'B,2', 'C,3']
DIAGONAL_DOWN_WIN_POSITIONS = ['A,3', 'B,2', 'C,1']
